services:
  server:
    build:
      context: .
    environment:
      NODE_ENV: development
    ports:
      - 5000:5000
    env_file:
      - .env
    volumes:
      - ./src:/usr/src/app/src
    develop:
      watch:
        - path: ./package.json
          action: rebuild
        - path: ./package-lock.json
          action: rebuild
